export const BOOK_WORLDS = [
  {
    id: "foreword",
    number: "00",
    label: "Foreword",
    title: "A mind between worlds.",
    paper: "#f1ede3",
    ink: "#243c32",
    accent: "#9c482e",
    motif: "The person behind the work",
  },
  {
    id: "atlas",
    number: "↗",
    label: "The atlas",
    title: "Pull a different thread.",
    paper: "#101b18",
    ink: "#f1ecdf",
    accent: "#cf9b73",
    motif: "Nine leaves. No straight lines.",
  },
  {
    id: "projects",
    number: "01",
    label: "Projects",
    title: "The workshop",
    paper: "#101a18",
    ink: "#f1ece0",
    accent: "#cf9b73",
    motif: "Ideas with fingerprints",
  },
  {
    id: "research",
    number: "02",
    label: "Research",
    title: "The observatory",
    paper: "#132b32",
    ink: "#eee9d7",
    accent: "#d3bc79",
    motif: "Stay with the question",
  },
  {
    id: "experience",
    number: "03",
    label: "Experience",
    title: "The gathering",
    paper: "#171b1c",
    ink: "#fff0d7",
    accent: "#cf9b73",
    motif: "Nothing worthwhile is built alone",
  },
  {
    id: "education",
    number: "04",
    label: "Education",
    title: "The foundations",
    paper: "#e8ebe2",
    ink: "#263b33",
    accent: "#996240",
    motif: "A map, not a finish line",
  },
  {
    id: "certifications",
    number: "05",
    label: "Certifications",
    title: "The reading room",
    paper: "#ede6d8",
    ink: "#50382d",
    accent: "#8f472e",
    motif: "Keep the curiosity. Keep the proof.",
  },
  {
    id: "achievements",
    number: "06",
    label: "Achievements",
    title: "The constellation",
    paper: "#121615",
    ink: "#f6ebd4",
    accent: "#cf9b73",
    motif: "Small moments. Lasting marks.",
  },
  {
    id: "connect",
    number: "07",
    label: "Links & CVs",
    title: "The unwritten page",
    paper: "#13352c",
    ink: "#fff0d7",
    accent: "#cf9b73",
    motif: "What shall we make next?",
  },
] as const;
export type BookWorldId = (typeof BOOK_WORLDS)[number]["id"];
