export const BOOK_WORLDS = [
  {
    id: "foreword",
    number: "00",
    label: "Foreword",
    title: "A mind between worlds.",
    paper: "#f2ead8",
    ink: "#243c32",
    accent: "#9c482e",
    motif: "The person behind the work",
  },
  {
    id: "atlas",
    number: "↗",
    label: "The atlas",
    title: "Pull a different thread.",
    paper: "#e8dfce",
    ink: "#433f30",
    accent: "#955139",
    motif: "Nine leaves. No straight lines.",
  },
  {
    id: "projects",
    number: "01",
    label: "Projects",
    title: "The workshop",
    paper: "#efe2ce",
    ink: "#4b3025",
    accent: "#a64527",
    motif: "Ideas with fingerprints",
  },
  {
    id: "research",
    number: "02",
    label: "Research",
    title: "The observatory",
    paper: "#19343b",
    ink: "#eee9d7",
    accent: "#d3bc79",
    motif: "Stay with the question",
  },
  {
    id: "experience",
    number: "03",
    label: "Experience",
    title: "The gathering",
    paper: "#803e32",
    ink: "#fff0d7",
    accent: "#ead0a4",
    motif: "Nothing worthwhile is built alone",
  },
  {
    id: "education",
    number: "04",
    label: "Education",
    title: "The foundations",
    paper: "#d8e4df",
    ink: "#294c46",
    accent: "#915538",
    motif: "A map, not a finish line",
  },
  {
    id: "certifications",
    number: "05",
    label: "Certifications",
    title: "The reading room",
    paper: "#ece0ca",
    ink: "#50382d",
    accent: "#8f472e",
    motif: "Keep the curiosity. Keep the proof.",
  },
  {
    id: "achievements",
    number: "06",
    label: "Achievements",
    title: "The constellation",
    paper: "#282722",
    ink: "#f6ebd4",
    accent: "#d5b772",
    motif: "Small moments. Lasting marks.",
  },
  {
    id: "connect",
    number: "07",
    label: "Links & CVs",
    title: "The unwritten page",
    paper: "#22443a",
    ink: "#fff0d7",
    accent: "#e3be87",
    motif: "What shall we make next?",
  },
] as const;
export type BookWorldId = (typeof BOOK_WORLDS)[number]["id"];
